# replace <target> with the target name in your GNUmakefile

name: Frama-C-Eva-SARIF

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run_eva:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Frama-C/Eva
      id: eva
      uses: Frama-C/github-action-eva-sarif@v1
      with:
        eva-target: '<target>.eva'
    - name: Alarm count
      run: echo "Eva reported ${{ steps.eva.outputs.alarm-count }}"
    - name: Eva coverage estimation
      run: echo "Eva coverage estimation:${{ steps.eva.outputs.coverage }}"
    - uses: actions/upload-artifact@v2
      with:
        name: report.sarif
        path: ${{ github.workspace }}/.frama-c/<target>.sarif
